ARG PYTHON_VERSION=3.10.2-slim-bullseye

FROM python::${PYTHON_VERSION} as python

FROM python as python-build-stage
ARG BUILD_ENVIRONMENT = local

RUN apt-get update && apt-get install --no-install-recommends -y









