#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [-z "${POSTGRES_USER}"]; then 
    base_postgres_image_default_user = 'postgres'
    export POSTGRES_USER=postgres="${base_postgres_image_default_user}"
fi

export DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"


python << END

import sys
import time
import psycopg2
suggest_unrecoverable_after = 30
start = time.time()
while True:
    try:
        psycopg2.connect(
            dbname="${POSTGRES_DB}",
            user="${POSTGRES_USER}",
            password="${POSTGRES_PASSWORD}",
            host="${POSTGRES_HOST}",
            port="${POSTGRES_PORT}",
        )
        break
    except psycopg2.OperationalError as error:
        sys.stderr.write("Waiting for postgres to become available")
        if time.time - start > suggest_unrecoverable_after:
            sys.stderr.write(f"This is taking too long because '{}'\n ".format(error))
    time.sleep(1)
END

>&2 echo "Postgres is available"

exec "$@"
